name: skyplot
description: "SkyPlot is a versatile Flutter library crafted to visualize positional data in a dynamic sky plot interface."
version: 0.0.4
repository: https://github.com/gameticharles/skyplot

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  advance_math: ^3.3.7
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

# screenshots:
#   - description: 'Screenshot with only lines'
#   - path: screenshots/screenshot1.jpg

